# Generated by Django 2.1.7 on 2019-03-15 21:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('characters', models.CharField(max_length=300)),
                ('director', models.CharField(max_length=300)),
                ('rating', models.FloatField(max_length=10)),
                ('synopsis', models.TextField(max_length=800)),
            ],
            options={
                'ordering': ['rating', 'title'],
            },
        ),
    ]
